vich_uploader:
    db_driver: orm

    mappings:
        kamer_thumbnails:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_path%'

        kamer_kamerimages:
          uri_prefix: '%uploads_path%'
          upload_destination: '%kernel.project_dir%/public/%uploads_path%'
