<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Kamer extends \App\Entity\Kamer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'naam', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'personen', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'oppervlakte', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'omschrijving', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'prijslaagseizoen', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'prijshoogseizoen', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'reservaties', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'diensts', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'thumbnail', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'thumbnailFile', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'kamerImages'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'naam', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'personen', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'oppervlakte', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'omschrijving', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'prijslaagseizoen', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'prijshoogseizoen', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'reservaties', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'diensts', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'thumbnail', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'thumbnailFile', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Kamer' . "\0" . 'kamerImages'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Kamer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getThumbnailFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThumbnailFile', []);

        return parent::getThumbnailFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setThumbnailFile($thumbnailFile): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThumbnailFile', [$thumbnailFile]);

        parent::setThumbnailFile($thumbnailFile);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNaam(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaam', []);

        return parent::getNaam();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaam(string $naam): \App\Entity\Kamer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaam', [$naam]);

        return parent::setNaam($naam);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonen(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonen', []);

        return parent::getPersonen();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonen(int $personen): \App\Entity\Kamer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonen', [$personen]);

        return parent::setPersonen($personen);
    }

    /**
     * {@inheritDoc}
     */
    public function getOppervlakte(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOppervlakte', []);

        return parent::getOppervlakte();
    }

    /**
     * {@inheritDoc}
     */
    public function setOppervlakte(int $oppervlakte): \App\Entity\Kamer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOppervlakte', [$oppervlakte]);

        return parent::setOppervlakte($oppervlakte);
    }

    /**
     * {@inheritDoc}
     */
    public function getOmschrijving(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOmschrijving', []);

        return parent::getOmschrijving();
    }

    /**
     * {@inheritDoc}
     */
    public function setOmschrijving(string $omschrijving): \App\Entity\Kamer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOmschrijving', [$omschrijving]);

        return parent::setOmschrijving($omschrijving);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrijslaagseizoen(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrijslaagseizoen', []);

        return parent::getPrijslaagseizoen();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrijslaagseizoen(float $prijslaagseizoen): \App\Entity\Kamer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrijslaagseizoen', [$prijslaagseizoen]);

        return parent::setPrijslaagseizoen($prijslaagseizoen);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrijshoogseizoen(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrijshoogseizoen', []);

        return parent::getPrijshoogseizoen();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrijshoogseizoen(float $prijshoogseizoen): \App\Entity\Kamer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrijshoogseizoen', [$prijshoogseizoen]);

        return parent::setPrijshoogseizoen($prijshoogseizoen);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservaties(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservaties', []);

        return parent::getReservaties();
    }

    /**
     * {@inheritDoc}
     */
    public function addReservaty(\App\Entity\Reservatie $reservaty): \App\Entity\Kamer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReservaty', [$reservaty]);

        return parent::addReservaty($reservaty);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReservaty(\App\Entity\Reservatie $reservaty): \App\Entity\Kamer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReservaty', [$reservaty]);

        return parent::removeReservaty($reservaty);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiensts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiensts', []);

        return parent::getDiensts();
    }

    /**
     * {@inheritDoc}
     */
    public function addDienst(\App\Entity\Dienst $dienst): \App\Entity\Kamer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDienst', [$dienst]);

        return parent::addDienst($dienst);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDienst(\App\Entity\Dienst $dienst): \App\Entity\Kamer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDienst', [$dienst]);

        return parent::removeDienst($dienst);
    }

    /**
     * {@inheritDoc}
     */
    public function getThumbnail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThumbnail', []);

        return parent::getThumbnail();
    }

    /**
     * {@inheritDoc}
     */
    public function setThumbnail(?string $thumbnail): \App\Entity\Kamer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThumbnail', [$thumbnail]);

        return parent::setThumbnail($thumbnail);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): \App\Entity\Kamer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeInterface $updatedAt): \App\Entity\Kamer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getKamerImages(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKamerImages', []);

        return parent::getKamerImages();
    }

    /**
     * {@inheritDoc}
     */
    public function addKamerImage(\App\Entity\KamerImage $kamerImage): \App\Entity\Kamer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addKamerImage', [$kamerImage]);

        return parent::addKamerImage($kamerImage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeKamerImage(\App\Entity\KamerImage $kamerImage): \App\Entity\Kamer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeKamerImage', [$kamerImage]);

        return parent::removeKamerImage($kamerImage);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
