<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKrzN8Jc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKrzN8Jc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKrzN8Jc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKrzN8Jc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKrzN8Jc\App_KernelDevDebugContainer([
    'container.build_hash' => 'KrzN8Jc',
    'container.build_id' => 'ae6e03bb',
    'container.build_time' => 1590493121,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKrzN8Jc');
